services:
  wasp-api:
    container_name: wasp-api
    build:
      context: .
    restart: unless-stopped
    networks:
      - hive
    env_file:
      - stack.env

networks:
  hive:
    external: true
